name: build
'on':
  push:
    branches:
      - pdm_migration
  pull_request:
    branches:
      - pdm_migration
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env: 
      CONSUL_VERSION: '0.7.4'
      CONSUL_DIR: '$HOME/consul_$CONSUL_VERSION'
      CONSUL_ZIPNAME: 'consul_${CONSUL_VERSION}_linux_amd64.zip'

    steps:
      - name: 'Set up Python 2.7'
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'
      - uses: actions/checkout@v2
      - run: >-
          if [[ ! -f $HOME/consul_0.7.4/consul ]]; then (mkdir -p $HOME/consul_0.7.4 && cd $HOME/consul_0.7.4 && wget https://releases.hashicorp.com/consul/0.7.4/consul_0.7.4_linux_amd64.zip && unzip consul_0.7.4_linux_amd64.zip); fi
      - run: $HOME/consul_0.7.4/consul --version
      - run: $HOME/consul_0.7.4/consul agent -dev -log-level=warn &
      - run: >-
          wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
      - run: chmod +x miniconda.sh
      - run: ./miniconda.sh -b
      - run: 'export PATH=$HOME/miniconda2/bin:$PATH'
      - run: conda update --yes conda
      - run: conda env create -f conda_env_linux64.yml
      - run: conda init bash
      - run: source /usr/share/miniconda/etc/profile.d/conda.sh
      - run: eval "$(conda shell.bash hook)"
      - run: conda activate mi
      - run: >-
          psql -c 'create role awips superuser createdb createrole inherit
          login;' -U postgres
      - run: psql -c 'create database metadata;' -U postgres
      - run: >-
          psql -c 'grant all privileges on database metadata to awips;' -U postgres
      - run: nosetests -a UNIT --with-coverage --cover-package=mi

